feign:
   hystrix:
      enabled: true
management:
   endpoints:
      web:
         exposure:
            include: refresh,health,hystrix.stream
server:
   port: 8001
spring:
   application:
      name: consumer-feign
   zipkin:
      base-url: http://localhost:9111
   sleuth:
      sampler:
         probability: 1.0