eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7777
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9111
  sleuth:
    sampler:
      probability: 1.0
zuul:
  routes:
    api-a:
      path: /ribbon/**
      serviceId: consumer-ribbon
    api-b:
      path: /feign/**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
      serviceId: consumer-feign
      

